// <auto-generated />
namespace AulaEF_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PersonMobileMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonMobileMail));
        
        string IMigrationMetadata.Id
        {
            get { return "202210101530271_PersonMobileMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
